// Builds project/support.js: React + ReactDOM (MIT, runtime/vendor) followed by the Husna preview runtime.
// Every .dc.html loads ./support.js, so with this one file in place the screens run on any static host.
//   node tools/build-support.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(join(root, p), 'utf8');
const out = [
  '/* Generated by tools/build-support.mjs. Do not edit; edit runtime/dc-runtime.js and rebuild. */',
  read('runtime/vendor/react.production.min.js'),
  read('runtime/vendor/react-dom.production.min.js'),
  read('runtime/dc-runtime.js'),
].join('\n;\n');
writeFileSync(join(root, 'project/support.js'), out);
console.log('project/support.js', out.length, 'bytes');
